export const localization = {
  common: {
    price: "قیمت",
    inventory: "موجودی",
    description: "توضیحات",
    brand: "برند",
    rial: "ریال",
    logout: "خروج",
    quantity: "تعداد",
    yes: "بله",
    no: "خیر",
  },
  home: {
    menuList: {
      home: "خانه",
      marayedCoffee: "قهوه های مراید",
      foreignCoffee: "قهوه های خارجی",
      InstantCoffee: "قهوه های فوری",
      coffeeMakers: "قهوه سازها",
      accessories: "لوازم جانبی",
      arabicaCoffee: "قهوه عربیکا",
      robustaCoffee: "قهوه ربوستا",
      turkCoffee: "قهوه ترک",
      mixCoffee: "قهوه ترکیبی",
      lavazaCoffee: "قهوه لاوازا",
      eliCoffee: "قهوه الی",
      starbucksCoffee: "قهوه استارباکس",
      mazdaCoffee: "قهوه مزتا",
      jacobsCoffee: "قهوه جاکوبز",
      davidovCoffee: "قهوه دیویدوف",
      NestléCoffee: "قهوه نستله",
      filterCoffee: "فیلتر قهوه ساز",
      grinderCoffee: "آسیاب قهوه",
      mokapat: "موکاپات",
      frenchPress: "فرنچ پرس",
      electricEspressoMachine: "اسپرسو ساز برقی",
      loginOrSignUp: "ورود/ثبت نام",
      myAccount: "حساب کاربری من",
    },
    typeCoffee: "انواع قهوه",
    typeCoffeeMaker: "ابزار دم آوری قهوه",
    showAllProducts: "مشاهده تمام محصولات",
    sampleOfProducts: "نمونه محصولات",
  },
  auth: {
    email: "ایمیل",
    password: "رمز عبور",
    address: "آدرس",
    firstname: "نام",
    lastname: "نام خانوادگی",
    username: "نام کاربری",
    phoneNumber: "شماره تلفن همراه",
    submit: "ثبت نام",
    login: "ورود",
    submitPage: "صفحه ثبت نام",
    loginPage: "صفحه ورود",
    errorMessage: "پر کردن این فیلد الزامی است",
    registerSuccess: "ثبت نام با موفقیت انجام شد",
    registerFail: "این نام کاربری قبلا ثبت نام شده",
    loginSuccess: "ورود شما با موفقیت انجام شد",
    loginFail: "نام کاربری یا رمز عبور اشتباه است",
    validation: {
      errorEmptyField: "پر کردن این فیلد الزامی است",
      errorPasswordRegex: "رمز عبور باید ترکیبی از کاراکتر و عدد باشد",
      errorPasswordLength: "رمز عبور حداقل باید هشت رقم باشد",
    },
  },
  dashboard: {
    adminPanel: "پنل ادمین",
    products: "کالاها",
    product: "کالا",
    InventoryAndPrices: "موجودی و قیمت ها",
    orders: "سفارش ها",
    addProduct: "افزودن کالا",
    save: "ذخیره",
    deliveredOrders: "سفارش های تحویل داده شده",
    ordersPendingShipment: "سفارش های در انتظار ارسال",
    edit: "ویرایش",
    delete: "حذف",
    checkOrder: "برسی سفارش",
    totalAmount: "مجموع مبلغ",
    orderRegistrationTime: "زمان ثبت سفارش",
    category: "دسته بندی",
    picture: "تصویر",
    nameProduct: "نام کالا",
    actions: "اقدامات",
    table: "جدول",
    username: "نام کاربر",
    addAndEditProduct: "افزودن/ویرایش کالا ",
    uploadPicture: "آپلود تصویر",
    subCategory: "زیر دسته",
    questionDeleteProduct: "آیا می خواهید این محصول را حذف کنید؟",
    successAddProduct: "محصول با موفقیت افزوده شد",
    failAddProduct: "محصول اضافه نشد",
    successEditProduct: "محصول با موفقیت ویرایش شد",
    failEditProduct: "محصول ویرایش نشد",
    deleteProduct: "محصول از جدول محصولات حذف شد",
  },
  cart: {
    basket: "سبد خرید",
    noProduct: "هیچ محصولی در سبد خرید نیست",
    backToShop: "بازگشت به فروشگاه",
  },
};
