export const localization = {
  common: {
    price: "قیمت",
    inventory: "موجودی",
    description: "توضیحات",
    brand: "برند",
    rial: "ریال",
    logout: "خروج",
    quantity: "تعداد",
    yes: "بله",
    no: "خیر",
    addProductToBasket: "افزودن به سبد خرید",
    filterQuantity: "مرتب سازی براساس موجودی",
    filterOlder: "مرتب سازی براساس قدیمی ترین",
    filterNewer: "مرتب سازی براساس جدید ترین",
    filterHighPrice: "مرتب سازی براساس گرانترین",
    filterLowPrice: "مرتب سازی براساس ارزانترین",
    showFilter: "مشاهده فیلترها",
    pageFilter: "صفحه فیلترها",
    filterCategory: "فیلتر براساس دسته",
    filterSubCategory: "فیلتر براساس زیر دسته",
    submitFilter: "اعمال فیلتر",
  },
  home: {
    menuList: {
      home: "خانه",
      marayedCoffee: "قهوه های مراید",
      foreignCoffee: "قهوه های خارجی",
      InstantCoffee: "قهوه های فوری",
      coffeeMakers: "قهوه سازها",
      accessories: "لوازم جانبی",
      arabicaCoffee: "قهوه عربیکا",
      robustaCoffee: "قهوه ربوستا",
      turkCoffee: "قهوه ترک",
      mixCoffee: "قهوه ترکیبی",
      lavazaCoffee: "قهوه لاوازا",
      eliCoffee: "قهوه الی",
      starbucksCoffee: "قهوه استارباکس",
      mazdaCoffee: "قهوه مزتا",
      jacobsCoffee: "قهوه جاکوبز",
      davidovCoffee: "قهوه دیویدوف",
      NestléCoffee: "قهوه نستله",
      filterCoffee: "فیلتر قهوه ساز",
      grinderCoffee: "آسیاب قهوه",
      mokapat: "موکاپات",
      frenchPress: "فرنچ پرس",
      electricEspressoMachine: "اسپرسو ساز برقی",
      loginOrSignUp: "ورود/ثبت نام",
      myAccount: "حساب کاربری من",
    },
    typeCoffee: "انواع قهوه",
    typeCoffeeMaker: "ابزار دم آوری قهوه",
    showAllProducts: "مشاهده تمام محصولات",
    sampleOfProducts: "نمونه محصولات",
    searchProducts: "جستجوی محصول",
    buyCoffee: "خرید قهوه",
    desBuyCoffee:
      "خرید آنلاین قهوه از فروشگاه قهوه مراید می‌تواند یک تجربه‌ی شگفت‌انگیز برای شما باشد، به خصوص زمانی که شما به دنبال قهوه‌ ای با کیفیت بالا و تازگی و طراوت فوق‌ العاده از قهوه خود هستید. فروشگاه اینترنتی قهوه مراید، به شما این امکان را می‌دهد تا به راحتی و با اطمینان، قهوه‌ی مورد نظر خود را از میان انواع مختلفی دانه قهوه که در این فروشگاه موجود است، انتخاب نمایید.",
    buyOnlineCoffee: "خرید آنلاین قهوه",
    desBuyOnlineCoffee:
      "از فروشگاه قهوه مراید دارای مزایای بسیاری است که در ادامه به شما بیان خواهیم کرد. قهوه مراید مجموعه ایست در زمینه خرید قهوه و فروش قهوه اینترنتی و ارائه انواع دانه قهوه و قهوه های آسیاب شده همچنین لوازم و تجهیزات و دستگاه های خانگی حرفه ای به مشتریان خانگی و قهوه فروشی ها، کافی شاپ ها، رستوران ها و... فعالیت می کند. مجموعه ما از سال ۱۳۸۴ تا به امروز در زمینه روست و ترکیب قهوه های مخصوص و ممتاز و همچنین ارائه برند های معتبر در زمینه قهوه برند و کپسول قهوه لوازم و تجهیزات حرفه ای و خانگی + انواع کافی میکس مشغول می باشد.",
    shopCoffeeMarayed: "قهوه فروشی مراید",
    desShopCoffeeMarayed:
      "سایت قهوه ملو با هدف ارائه محصولات و خدمات بصورت اینترنتی به دوست داران قهوه  از سال ۹۲ شروع به فعالیت خود نمود و در این راستا تا به امروز به بیش از چند ده هزار مشتری اعم از خانگی و قهوه فروشی ها، کافی شاپ ها... خدمت رسانی نموده. هدف از ارائه محصولات بصورت اینترنتی دسترسی هر چه راحت تر مشتریان برای دسترسی به اطلاعات محصولات متفاوت در زمینه قهوه و نوشیدنی می باشد و همچنین سهولت خرید و دسترسی به محصولات مورد نظر به مشتریان.",
    freeSend: "ارسال رایگان",
    desFreeSen:
      "مشتریان قهوه ملو میتوانند، به آسانی و باخیالی آسوده اقدام به خرید قهوه باکیفیت و مرغوب که مد نظرشان میباشند، از این مجموعه نمایند، و در صورتی که در شهر تهران باشند، در سریع ترین بازه زمانی ممکن، (بازه زمانی مد نظر مشتری)، سفارش خود را در یافت نمایند، و برای سایر شهر ها بازه زمانی دریافت سفارش، حداکثر دو الی سه روز کاری میباشد. لازم به ذکر است که تمام سفارش های بالای 500 هزار تومان به صورت ارسال رایگان، میباشد، و هیچگونه هزینه ای از مشتری دریافت نمیگردد.",
  },

  auth: {
    email: "ایمیل",
    password: "رمز عبور",
    address: "آدرس",
    firstname: "نام",
    lastname: "نام خانوادگی",
    username: "نام کاربری",
    phoneNumber: "شماره تلفن همراه",
    submit: "ثبت نام",
    login: "ورود",
    submitPage: "صفحه ثبت نام",
    loginPage: "صفحه ورود",
    errorMessage: "پر کردن این فیلد الزامی است",
    registerSuccess: "ثبت نام با موفقیت انجام شد",
    registerFail: "این نام کاربری قبلا ثبت نام شده",
    loginSuccess: "ورود شما با موفقیت انجام شد",
    loginFail: "نام کاربری یا رمز عبور اشتباه است",
    validation: {
      errorEmptyField: "پر کردن این فیلد الزامی است",
      errorPasswordRegex: "رمز عبور باید ترکیبی از کاراکتر و عدد باشد",
      errorPasswordLength: "رمز عبور حداقل باید هشت رقم باشد",
    },
  },
  dashboard: {
    adminPanel: "پنل ادمین",
    products: "کالاها",
    product: "کالا",
    InventoryAndPrices: "موجودی و قیمت ها",
    orders: "سفارش ها",
    addProduct: "افزودن کالا",
    save: "ذخیره",
    deliveredOrders: "سفارش های تحویل داده شده",
    ordersPendingShipment: "سفارش های در انتظار ارسال",
    edit: "ویرایش",
    delete: "حذف",
    checkOrder: "برسی سفارش",
    totalAmount: "مجموع مبلغ",
    orderRegistrationTime: "زمان ثبت سفارش",
    category: "دسته بندی",
    picture: "تصویر",
    nameProduct: "نام کالا",
    actions: "اقدامات",
    table: "جدول",
    username: "نام کاربر",
    addAndEditProduct: "افزودن/ویرایش کالا ",
    uploadPicture: "آپلود تصویر",
    subCategory: "زیر دسته",
    questionDeleteProduct: "آیا می خواهید این محصول را حذف کنید؟",
    successAddProduct: "محصول با موفقیت افزوده شد",
    failAddProduct: "محصول اضافه نشد",
    successEditProduct: "محصول با موفقیت ویرایش شد",
    failEditProduct: "محصول ویرایش نشد",
    deleteProduct: "محصول از جدول محصولات حذف شد",
    olderPicture: "عکس فعلی",
    newerPicture: "عکس جدید",
    noPicture: "عکسی آپلود نشده",
    showOrder: "نمایش سفارش",
    customer: "نام مشتری",
    address: "آدرس",
    mobile: "شماره موبایل",
    delivaryDate: "زمان تحویل",
    createdDate: "زمان سفارش",
    delivary: "تحویل",
    noOrders: "هیچ سفارشی در جدول وجود ندارد",
  },
  cart: {
    basket: "سبد خرید",
    noProduct: "هیچ محصولی در سبد خرید نیست",
    backToShop: "بازگشت به فروشگاه",
    showBasket: "مشاهده سبد خرید",
    payment: "تسویه حساب",
    total: "جمع جزء",
    product: "محصول",
    quantity: "تعداد",
    totalBasketCart: "جمع کل سبد خرید",
    transport: "حمل و نقل",
    totalPrice: "مجموع",
    continuePayment: "ادامه جهت تسویه حساب",
    messageTransportation: "هزینه ارسال : ۳۰۰,۰۰۰ریال",
    questionDeleteCart: "آیا می خواهید این محصول را از سبد خرید حذف کنید؟",
    messageDeleteCart: "محصول مورد نظر با موفقیت حذف شد",
    messageAddCartToBasket: "محصول با موفقیت به سبد خرید شما افزوده شد",
    continueBuy: "ادامه خرید",
    messageGratherQuantity:
      "مقدار انتخاب شده بیشتر از موجودی این کالا در انبار است",
  },
  footerRoot: {
    instantLink: "لینک های سریع",
    accountUser: "حساب کاربری",
    contactUs: "تماس با ما",
    electronicTrustSymbol: "نماد اعتماد الکترونیک",
    nationalUnionSymbol: "نماد اتحادیه کشوری",
    organizationSymbol: "نماد ساماندهی",
    addressShop: "آدرس فروشگاه ها",
    hourWorkShop: "ساعات کاری فروشگاه",
    articleCoffee: "مقاله قهوه",
    brandCoffee: "قهوه برند",
    panelUser: "پنل کاربری",
    purchaseGuide: "راهنمای خرید",
    orderTracking: "پیگیری سفارش",
    whatsApp: "واتساپ: 09377489675",
    mobile: "شماره تلفن: 02166426784",
    email: "ایمیل : Info (a) melocoffee.com",
    branchShomail: "شعبه بهار شمالی: خ بهار شمالی پ 342",
    internetVahed: "واحد اینترنتی: خ بهار شمالی پ 342",
    branchValiaser: "شعبه میدان ولیعصر: ضلع شرقی میدان ولی عصر",
    internet: "اینترنتی: 10 صبح تا 17 بعد از ظهر",
    thursday: "پنجشنبه: 10 صبح تا 14 بعد از ظهر",
    branchBahar: "شعبه خیابان بهار",
    tenToNight: "10 صبح تا 9 شب",
    branchValiaser2: "شعبه خیابان ولیعصر",
    eightToTen: "8 صبح تا 10 شب",
    copyRight: "تمامی حقوق این سایت متعلق به فروشگاه مراید می باشد",
  },
  shop: {
    shopInternet: "فروشگاه اینترنتی",
    moreProducts: "مشاهده محصول بیشتر",
    unavailable: "ناموجود",
    available: "موجود در انبار",
  },
  singleProduct: {
    productID: "شناسه محصول",
    category: "دسته",
    shared: "اشتراک گذاری",
    productsRelated: "محصولات مرتبط",
  },
  payment: {
    factorPayment: "صورت حساب و حمل و نقل",
    state: "استان",
    city: "شهر",
    placeholderState: "لطفا استان مورد نظر را انتخاب کنید",
    placeholderCity: "لطفا شهر مورد نظر را انتخاب کنید",
    orderNotes: "یادداشت های سفارش",
    placeholderOrderNotes:
      "نکته ای درباره سفارش یا زمان ارسال دارید ؟ در این قسمت یاداشت خود را بنویسید",
    order: "سفارش شما",
    pasian: "درگاه پرداخت بانک پارسیان",
    zarin: "پرداخت امن زرین پال",
    warningMessage:
      "لطفا قبل از ثبت سفارش تمامی قوانین و مقررات موجود در وب سایت را مطالعه نموده و با زدن تیک زیر توافق خود را با آن اعلام کنید",
    messageCheckBox: "من شرایط و مقررات سایت را خوانده ام و آن را می پذیرم. *",
    submitOrder: "ثبت سفارش",
    warningTickMessage: "لطفا تیک مقررات و قوانین را بزنید",
  },
  resultPayment: {
    internetPortal: "درگاه اینترنتی",
    questionResultPayment: "آیا از خرید خود مطمئن هستید؟",
    pay: "پرداخت",
    cancel: "انصراف",
    successPaymentTitle: "ممنون از اعتماد شما",
    successPaymentBody:
      "پرداخت شما با موفقیت انجام شد و در لیست انتظار قرار گرفت",
    backToHome: "بازگشت به صفحه اصلی",
    failPaymentTitle: "پرداخت ناموفق",
    failPaymentBody: "متاسفانه مشکلی در پرداخت به وجود آمد",
  },
};
