export const localization = {
  home: {
    menuList: {
      home: "خانه",
      marayedCoffee: "قهوه های مراید",
      foreignCoffee: "قهوه های خارجی",
      InstantCoffee: "قهوه های فوری",
      coffeeMakers: "قهوه سازها",
      accessories: "لوازم جانبی",
      arabicaCoffee: "قهوه عربیکا",
      robustaCoffee: "قهوه ربوستا",
      turkCoffee: "قهوه ترک",
      loginOrSignUp: "ورود/ثبت نام",
    },
  },
  auth: {
    email: "ایمیل",
    password: "رمز عبور",
    address: "آدرس",
    firstname: "نام",
    lastname: "نام خانوادگی",
    username: "نام کاربری",
    phoneNumber: "شماره تلفن همراه",
    submit: "ثبت نام",
    login: "ورود",
    submitPage: "صفحه ثبت نام",
    loginPage: "صفحه ورود",
    errorMessage: "پر کردن این فیلد الزامی است",
    registerSuccess: "ثبت نام با موفقیت انجام شد",
    registerFail: "ثبت نام ",
  },
};
