// export const slugs = [
//   "marayed-coffees",
//   "foreign-coffees",
//   "instant-coffees",
//   "accessories",
//   "coffee-makers",
//   "arabica",
//   "robusta",
//   "turk",
//   "mix",
//   "lavaza-coffee",
//   "eli's-coffee",
//   "starbucks-coffee",
//   "mazda-coffee",
//   "jacobs-coffee",
//   "davidov-coffee",
//   "nestle-coffee",
//   "filter-coffee",
//   "grinder-coffee",
//   "mokapat",
//   "french-press",
//   "electric-espresso-machine",
// ];

export const slugs = [
  ["marayed-coffees", "arabica", "robusta", "turk", "mix"],
  [
    "foreign-coffees",
    "lavaza-coffee",
    "eli's-coffee",
    "starbucks-coffee",
    "mazda-coffee",
  ],
  ["instant-coffees", "jacobs-coffee", "davidov-coffee", "nestle-coffee"],
  ["accessories", "filter-coffee", "grinder-coffee"],
  ["coffee-makers", "electric-espresso-machine", "mokapat", "french-press"],
];
